# Generated by Django 6.0.3 on 2026-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student_class',
            field=models.CharField(choices=[('PreKG', 'PreKG'), ('LKG', 'LKG'), ('UKG', 'UKG')], default='PreKG', max_length=20),
            preserve_default=False,
        ),
    ]
