# Generated by Django 6.0.3 on 2026-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_homework_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.AddField(
            model_name='marks',
            name='comments',
            field=models.TextField(default='No comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.CharField(default='No comments', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='learning',
            field=models.CharField(default='No comments', max_length=100),
            preserve_default=False,
        ),
    ]
