# Generated by Django 6.0.3 on 2026-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_marks_marks_remove_marks_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
