# Generated by Django 6.0.3 on 2026-04-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teacherapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherApplication',
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
