# Generated by Django 6.0.3 on 2026-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_parentquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('PreKG', 'PreKG'), ('LKG', 'LKG'), ('UKG', 'UKG')], max_length=20)),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=10)),
                ('time_slot', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
    ]
