# Generated by Django 6.0.3 on 2026-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='send_to',
            field=models.CharField(choices=[('Students', 'Students'), ('Teachers', 'Teachers'), ('Both', 'Both')], default='Both', max_length=20),
        ),
    ]
