# Generated by Django 6.0.3 on 2026-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.CharField(choices=[('PreKG', 'Pre KG'), ('LKG', 'LKG'), ('UKG', 'UKG')], default='LKG', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
