# Generated by Django 6.0.3 on 2026-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_assigned_class_alter_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(choices=[('PreKG', 'PreKG'), ('LKG', 'LKG'), ('UKG', 'UKG')], default='PreKG', max_length=20),
            preserve_default=False,
        ),
    ]
