# Generated by Django 6.0.3 on 2026-04-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacherapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='teacher_class',
            field=models.CharField(blank=True, choices=[('PreKG', 'PreKG'), ('LKG', 'LKG'), ('UKG', 'UKG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='teacher123', max_length=100),
        ),
    ]
